#!/bin/bash
#Edited by Jacopo Tediosi, original author is SHelfinger ()
#It's colorful and it requires rev (sudo apt-get install rev)
#Remember to change with your SSH port inside CURRENT_IP variable
#Distributed under GPLv3
#==============================================================================
REV=$(which rev)
CURRENT_IP=$(netstat -putan | awk '/:22 / && /ESTABLISHED/ {split($5,result,":"); print result[1]}' | tail -n1)
LAST_IP=$(last -n 1 | head -n 1 | awk '{print $3}')
LAST_DATE=$(last -n 1 | head -n 1 | tail -n1 | awk '{ s = ""; for (i = 4; i <= NF; i++) s = s $i " "; print s }' | $REV | awk '{ s = ""; for (i = 2; i <= NF; i++) s = s $i " "; print s }' | $REV | sed -e 's/^[[:space:]]*//')

USERS_LOGGED_IN=$(w | sed '1d' | sed 's/^/  /')

echo -e "\033[0mCurrent IP: \033[1;32m$CURRENT_IP \033[0m- Last IP: \033[1;31m$LAST_IP \033[0m- Last Access: \033[1;33m$LAST_DATE\033[0m"
if (($(echo "$USERS_LOGGED_IN" | wc -l)>1)); then
	echo -e "$USERS_LOGGED_IN"
else
	echo -e "  No other ssh connections besides you"
fi
