#!/bin/bash
JAILS=(
    "sshd"
    "vsftpd"
    "customlogin"
)

echo
echo -e "Fail2ban stats:"

for JAIL in "${JAILS[@]}"
do
    JAIL_STATUS=$(fail2ban-client status "$JAIL")

    JAIL_TOTAL_BANNED=$(echo "$JAIL_STATUS" | grep -oP 'Total banned:\s*\K\d+')
    JAIL_CURR_BANNED=$(echo "$JAIL_STATUS" | grep -oP 'Currently banned:\s*\K\d+')
    JAIL_TOTAL_FAILED=$(echo "$JAIL_STATUS" | grep -oP 'Total failed:\s*\K\d+')
    JAIL_CURR_FAILED=$(echo "$JAIL_STATUS" | grep -oP 'Currently failed:\s*\K\d+')

    echo -e "  ${JAIL^^}:"
    echo -e "    $JAIL_TOTAL_FAILED total failed and $JAIL_CURR_FAILED currently failed"
    echo -e "    $JAIL_TOTAL_BANNED total banned and $JAIL_CURR_BANNED currently banned"
done
